add_newline = false
format = "$username$hostname$directory$git_branch$git_status$nodejs$python$cmd_duration$character"

[username]
show_always = false
format = "[$user]($style) "

[hostname]
ssh_only = true
format = "on [$hostname]($style) "

[directory]
format = "[$path]($style) "
truncation_length = 3
truncate_to_repo = false
style = "fg:#49d6e9"

[git_branch]
format = "[$symbol$branch]($style) "
symbol = "git:"
style = "fg:#df769b"

[git_status]
format = "([$all_status$ahead_behind]($style) )"
style = "fg:#e4b781"
staged = "+"
modified = "!"
deleted = "x"
renamed = ">"
untracked = "?"
ahead = " ahead:${count}"
behind = " behind:${count}"
diverged = " ahead:${ahead_count} behind:${behind_count}"

[nodejs]
format = "[node $version]($style) "

[python]
format = "[py $version]($style) "

[cmd_duration]
min_time = 1000
format = "[$duration]($style) "
style = "fg:#e4b781"

[character]
success_symbol = "[>](fg:#49e9a6)"
error_symbol = "[>](fg:#e66533)"
